# Generated by Django 3.1.7 on 2021-05-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event_time_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time_time',
            new_name='address',
        ),
    ]
