# Generated by Django 3.2.2 on 2021-05-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210522_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='size',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
